### PR TITLE
Get jsonld data by list param

### PR DESCRIPTION
**Pull request by rageofaxe**
https://github.com/webRunes/Default-WRIO-Theme/issues/87

### CODE REVIEW

**Comment by rageofaxe** [comment]
@spirinvladimir please review

**Comment by AlexeyAnshakov** [comment]
@spirinvladimir merged for test, but please review.

**Comment by AlexeyAnshakov** [comment]
@rageofaxe build with error
https://travis-ci.org/webRunes/WRIO-InternetOS

P.S. please don't forget to link with issue: https://github.com/webRunes/Default-WRIO-Theme/issues/87 has been added into description

**Comment by rageofaxe** [comment]
@AlexeyAnshakov error in global.js, I did not change this file. Actually I can try fix it

**Pull request merged**
